### ISSUE TITLE
incorrectly determining remaining

### ISSUE THREAD

**Issue by reduxdj** [scttcper/koa-simple-ratelimit#115]
https://github.com/scttcper/koa-simple-ratelimit/blob/8329782a46267cbcfaa3b544a132c0dc088aea3a/index.js#L85

```    const headers = {
      [remaining]: opts.n,
      [reset]: t,
      [total]: opts.max,
    }
```

remaining should be opts.n  not opts.max

The debug statement is also incorrect

**Comment by scttcper** [comment]
i agree the debugger is wrong, but right there you do want the max - 1. The headers are adjusted again lower in the function look for `ctx.set(remaining, n - 1);`

**Comment by reduxdj** [comment]
ok, thanks for clarifying, the above change would have really no affect, since you are right, you are setting the remaining on the header down below.
