### ISSUE TITLE
Major breaking change from v4->v5 of allowlist/blocklist renaming was unnecessary

### ISSUE THREAD

**Issue by niftylettuce** [scttcper/koa-simple-ratelimit#220]
Just commenting here - appreciate your work on this, just commenting my opinion that this was an unnecessary change.  Not many packages completely change just the naming of something for not much reason.

**Comment by scttcper** [comment]
@niftylettuce I agree. Ready to take this package off my hands?

**Comment by niftylettuce** [comment]
If you want to transfer it over that's fine - I also don't mind where it is now since you already gave me collab/npm access 🙏 (thank you)
