### ISSUE TITLE
Deprecate in favor of @ladjs/koa-simple-ratelimit?

### ISSUE THREAD

**Issue by titanism** [scttcper/koa-simple-ratelimit#222]
Hello - we've forked this repo and modified it, added more tests to get 100% coverage, and added more options.

https://github.com/ladjs/koa-simple-ratelimit

Also, there is a core bug in this library; if the db/redis connection goes out, then the entire application will be inoperable due to the error thrown (e.g. 500 internal server error).  This is due to `await db.get` and `await db.pttl` calls in `src/index.ts`.

We've rewritten it and added plenty more tests.

If you'd like to deprecate this package, please archive it here on GitHub, and then add a note to the README instructing users to use https://github.com/ladjs/koa-simple-ratelimit instead.  If so, you'd also need to version bump and publish to npm (so the README with the verbiage shows on npm), then deprecate the entire package.

Thanks for writing and maintaining this library either way - and feel free to close this!

**Comment by scttcper** [comment]
I think @niftylettuce still uses this, I'll let them decide

**Comment by titanism** [comment]
We have discussed with them and you can archive and put a deprecation up to use `@ladjs/koa-simple-ratelimit`.  Thanks Scott!

**Comment by scttcper** [comment]
added the deprecation notice

**Comment by titanism** [comment]
Thank you @scttcper !
